'use strict';
module.exports = {
	user: {
		user: ['firstName', 'lastName', 'email', 'password', 'acceptedTC', 'phone', 'availability'],
		teamAdmin: ['rosters'],
		companyAdmin: [
			'firstName',
			'lastName',
			'email',
			'permission',
			'rosters',
			'status',
			'teams',
			'location',
			'roles',
			'adminTeams',
			'blocked',
			'org',
		],
		accountManager: [
			'firstName',
			'lastName',
			'email',
			'permission',
			'rosters',
			'status',
			'teams',
			'location',
			'roles',
			'adminTeams',
			'blocked',
			'org',
		],
		superAdmin: ['all'],
	},
	team: {
		user: [],
		teamAdmin: ['rosters'],
		companyAdmin: ['all'],
		accountManager: ['all'],
		superAdmin: ['all'],
	},
	org: {
		user: [],
		teamAdmin: [],
		companyAdmin: ['companyAdmins', 'teams'],
		accountManager: ['all'],
		superAdmin: ['all'],
	},
};
